### ISSUE TITLE
AN6.64:7.1; Aditi; The word *pare* isn't understandable.

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#112]
Again at an6.64:8.1, an6.64:9.1, an6.64:10.1, an6.64:11.1, an6.64:12.1.

**Comment by firepick1** [comment]
This was a surprisingly tricky fix. It turns out "pare" is both English and Pali, so Voice got very confused. Fortunately, Aditi is not used for English, so I was able to change the code to assume Pali for Aditi. We shall have to hope that no English translation uses the Pali word "pare"!

Fixed in v1.5.10

**Comment by sabbamitta** [comment]
In any case it sounds perfect on staging now. Thanks!
