### ISSUE TITLE
Voice has problems handling elisions for human voice recordings.

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#123]
#### Bug Description
See description [here](https://discourse.suttacentral.net/t/sc-voice-development-cycle-v1-6/13163/43?u=sabbamitta).

#### Discovered on:
 - OS: [e.g. Ubuntu 16.4]
 - Browser & Version: [e.g. chrome, safari]

**Comment by michaelh-sc** [comment]
This is caused by empty lines and Aeneas trying to fit things into what isn't recorded. Removing the empty lines fixes this. Manual segmentation to FIX this with the finetune aneas GUI I've discovered is not always accurate when fixing long suttas or when fine tuning twice.
So I may need to investigate a different way to fine tune the segmentation of long suttas using a different sync map format in different software such as Reaper rather than the Aeneas FineTune : https://www.readbeyond.it/aeneas/docs/syncmap.html#aeneas.syncmap.format.SyncMapFormat

**Comment by michaelh-sc** [comment]
Can be closed, manual segmentation check done. No way to discover what isn't recorded unless you listen to it! :) :)

**Comment by sabbamitta** [comment]
Thank you @michaelh-sc !

Closing.
