### ISSUE TITLE
Cannot add Admin user

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#130]
<kbd>Add User</kbd> does nothing.

**Comment by sabbamitta** [comment]
Hmm... I just tried out to add a new user on the production server, just for testing purposes. There it diesn't work either! So it must have come with one of our releases at some point... actually some time during v1.5, since before that it was working. I had created a "sabbamitta" user on the last staging server.

**Comment by sabbamitta** [comment]
I could now add user "sabbamitta" on staging. Thank you! Closing.
