### ISSUE TITLE
digitaloceanspaces catalog takes over 20 seconds

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#155]
Finding out what is stored in the bucket (i.e., the catalog) takes over 20 seconds, which a pretty severe impact.

**Comment by michaelh-sc** [comment]
Listing 4000 objects will always be expensive I think on any bucket provider. At what point does it call this? Perhaps a simple web request to where it's expected with a single retry might be better. Also make sure you're targeting the non-CDN URL, since the CDN URL only populated when someone tries to access it.

**Comment by firepick1** [comment]
I increased max-keys from 1000 to 16000, which made this go faster, but we have a long term issue with so many files in single bucket. I estimate we will have over 280,000 files, since each segment will have both an English and a Pali audio file and there are about 140,000 segments across 4000 suttas.  

Anagarika, I think light testing on several of Bhante's audio recordings in the Sutta Player would suffice. I listened to SN2.3 and it was fine. Thank you.

**Comment by michaelh-sc** [comment]
An alternate way of doing human-recorded audio is to simply use the full recording and display the text according to timing in the .json file or .srt - this would cut down on files, in case we wanted to go down that route - rather than using the segmented files.
Also we can run a list against an object key that is lower down (e.g. just the sutta path) rather than the whole bucket in a number of API calls?

**Comment by firepick1** [comment]
Confirm that new json structure is much faster to search using S3 prefix API. Thank you, Michael!
