### ISSUE TITLE
For SuttaCentral redirection to Voice, the translation language setting should default to the “lang” value from SC and override coockie settings

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#184]
#### Description

**Important:** @firepick1 , please keep a copy of the code for the language settings you wrote on Sept 27, 2019, just in case… !

**Note that for Norwegian and Japanese ISO language codes are different on SC and in Voice.**

#### Acceptance criteria 

- [ ] _What needs to be done for this issue to be completed_

**Comment by firepick1** [comment]
Fixed in v2.2.15.

For testing use this link, which simulates SuttaCentral DE language choice

https://54.67.25.233/scv/index.html#/sutta?search=an2.1-10&lang=de

What you will differ according to whether Voice settings are in cookies or not:

1. With settings in URL, Voice will determine website language for SC language
2. With settings in cookies, Voice will honor the cookie website language but use the SC translation language. 

Although Voice distinguishes between  website and translation language, SC does not. This introduces some ambiguity about website language. If the settings are in the URL, then Voice doesn't know what the user preference for website language is, so it just uses the SC language. If the settings are in the cookies, then Voice actually does know the user preference for website language even though the link is coming from SC.  SC's website language is currently always English.

Another subtlety is that if the user is looking at the Nyanatiloka Thera translation on SC, the SC link will show your translation in Voice because that is the segmented DE translation.

**Comment by sabbamitta** [comment]
:heavy_check_mark:
