### ISSUE TITLE
For a search term with an apostrophe the terminal search returns a `>` and stops there.

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#210]
#### Bug Description
For a search term with an apostrophe the terminal search returns a `>` and stops there:
```
sabbamitta@Sabbamitta-ThinkPad:~/Schreibtisch/SC-Voice/scv-bilara$ s I'll ask you
> 
```
Basically, I can't use that terminal window any more; it doesn't react to whatever I type. Or at least, I don't know what I should type.
#### Discovered on:
 - OS: [e.g. Ubuntu 16.4]
 - Browser & Version: [e.g. chrome, safari]

**Comment by firepick1** [comment]
This is a Linux issue that cannot be fixed by scv-bilara.  The command shell (aka. 'bash') treats quotes specially. In particular, distinction is made between single, double and backquotes, which are all special and magic. If you wanted the magic, that is wonderful. If you didn't want the magic, this is very distressing.  For this particular example, just double quote the search string

`./scripts/de-search "I'll ask you"`

https://blog.cloud66.com/bash-tricks-part-1-string-escaping/

**Comment by sabbamitta** [comment]
Thanks for teaching me new stuff! :smile: 

Closing.
