### ISSUE TITLE
Add setting for playlists "Pause between suttas" with default 2 sec, and configurable

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#237]
#### User story

When I use Voice it would be great if I were able to … because …

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ] 

#### Pre release planning check:
- [ ] Small enough to completed in a release.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by firepick1** [comment]
This is fixed in v2.2.13. The implementation inserts a one-second pause whenever it detects a change in the sutta_uid portion of the segment id. For suttas such as AN1.1-10, this will have no impact whatsoever since the segment id's are of the form "an1.1-10:...". However, the pause will appear in multi-sutta playlists (e.g., "mn1, mn2").

Regarding customization, we felt that is best achieved by simply hitting the Pause button on one's audio player. The newly introduced one-second pause provides ample opportunity to "take a meditation break" between suttas.  Automating such a feature as a user preference creates storage challenges on the web server given the large size of the downloaded audio files.

**Comment by sabbamitta** [comment]
:heavy_check_mark:
