### ISSUE TITLE
Fix broken search for "darkness light" (en) or "dunkelheit licht" (de)

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#238]
#### Bug Description
Search URL: https://35.176.193.204/scv/index.html?r=0.6645747870767343#/sutta?ips=6&lang=en&locale=de&maxResults=50&search=darkness%20light&showId=true&showLang=2&vnameRoot=sujato_pli&vnameTrans=Amy

See [here](https://discourse.suttacentral.net/t/sc-voice-development-cycle-2-1/14537/59?u=sabbamitta) and ff.

The same for "tor" or "toren" (de).

#### Discovered on:
 - OS: [e.g. Ubuntu 16.4]
 - Browser & Version: [e.g. chrome, safari]

**Comment by firepick1** [comment]
Fixed in v2.1.18. Problem with keyword search returning too many results.

**Comment by sabbamitta** [comment]
Testing: Works fine for "darkness light" and "dunkelheit licht", but not for "tor" or "toren"; and maybe still more.

**Comment by firepick1** [comment]
Testing: works now with toren. Toren was special because the search term only occurs in the title. There was code that looked only for non-title segments and that code returned nothing, which caused problems on the page. I changed the code to return the title segment now if there was no match in non-title segments. Both AN3.9 and AN3.10 only have Toren in the title segment. It doesn't occur in non-title segments. It's quite fascinating that a title isn't drawn from the body of the sutta, This implies that the Buddha did not title the sutta. Someone else did.

**Comment by sabbamitta** [comment]
> This implies that the Buddha did not title the sutta. Someone else did.

Of course he didn't. :-) Titles were added to the texts much later. But there are also suttas with "Toren" in the body of the text.

**Comment by sabbamitta** [comment]
"Tor" and "Toren" both work now, thank you! Closing.
