### ISSUE TITLE
Fix search results errors

### ISSUE THREAD

**Issue by Aminah-SC** [sc-voice/sc-voice#26]
#### Describe the bug

The following errors have been discovered:

  * Search for 'MN 1-50' or 'MN 1-10' returns "No suttas found"; and [other problems](https://discourse.suttacentral.net/t/suttacentral-voice-v1-0-0-released/11844/341?u=sabbamitta).
  * Search for sutta range such as AN10.1-50 sometimes fails with sutta not found for "bodhi"
  * :construction: "majjhimanikaya1-50" (with or without capital) brings results, namely 50 times DN 34!
  * The name Sabbamitta only occurs twice in the canon (search returns a few more suttas where it is not found).
  * Search for "ānapānassatisutta" finds nothing.

**Comment by firepick1** [comment]
This isn't really a bug. It's an Epic. It's also not clear to me why folks might want some of the following, which are all separate search features:

majjhimanikaya 1-50’ (with or without capital) brings no results.
‘MN 1-50’ or ‘mn 1-50’ brings no results.
‘MN’ as well as ‘mn’ brings results, namely a random selection of Majjhimanikaya Suttas.
‘MN1-50’ as well as ‘mn1-50’ brings results, namely a nicely ordered list of Majjhimanikaya Suttas from 1 to 50.
‘majjhimanikaya1-50’ (with or without capital) brings results, namely 50 times DN 34!

**Comment by Aminah-SC** [comment]
I definitely agree these are not all one issue. It took a whole bunch more time and effort than I hoped to set up the board so some quick cut-and-paste action was resorted to after a while! In fact, I'm not 100% clear what all of these refer to either, so at the very least, it's a good example of the point of trying to write up issues more clearly. 

Please go ahead and convert the issue to an Epic and relevant sub-issues so they work better for you.

**Comment by sabbamitta** [comment]
> The name Sabbamitta only occurs twice in the canon (search returns a few more suttas where it is not found).
Has been fixed in v1.6.16.

**Comment by firepick1** [comment]
We should close this issue--it's too vague and I don't know what the requirements are.  Then we should add individual issues for specific problems with desired outcomes.

**Comment by sabbamitta** [comment]
As we have discussed today we don't close it but look instead at the individual issues. :smiley_cat:

**Comment by sabbamitta** [comment]
- Search for 'MN 1-50' or 'MN 1-10' returns "No suttas found"---Fixed in v1.8 :heavy_check_mark: 
- Search for sutta range such as AN10.1-50 sometimes fails with sutta not found for "bodhi"---? Not clear what this means, so probably insoluble. Will not be addressed. 
- "majjhimanikaya1-50" (with or without capital) brings results, namely 50 times DN 34!---will not be addressed because no one will actually type that.
- The name Sabbamitta only occurs twice in the canon (search returns a few more suttas where it is not found)---Voice search now only finds Thag2.15, since it only searches the pALI which in DN14 has a different grammatical form, so is not found. Would require a new feature.
