### ISSUE TITLE
Paste in arbitrary Buddhist text for downloading MP3's

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#76]
#### User story

Some users would like to create MP3's not only from the content available on Voice but also from other Buddhist texts.

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ] Allow users to create MP3's of other content via Voice.

#### Pre release planning check:
- [ ] Small enough to completed in a release.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by Aminah-SC** [comment]
My view is this is outside of the scope of Voice.

**Comment by firepick1** [comment]
I agree that supporting randomTTS for the world is outside the scope of Voice, especially since we are accountable to AWS for services provided. However, it would probably make sense to break up the Voice monolith into smaller chunks for ease of maintenance. One of those chunks is the whole TTS cache, which is independent of sutta-central. That could go into a separate sc-voice-tts repository for use by others as they choose on their own AWS account. We ourselves currently have no need for that work to separate out the TTS part, so it is unlikely to happen.
